emergency_stop_distance: 0.2
emergency_stop_half_width: 0.25
min_obstacle_z: 0.15
max_obstacle_z: 1.5
es_min_range: 0.12
es_min_points: 3
es_trigger_frames: 2
es_release_frames: 2
base_frame: base_footprint
es_require_valid_tf: true
es_tf_fail_stop: true
cmd_vel_topic: /magv/omni_drive_controller/cmd_vel
odometry_topic: /magv/odometry/gt
pointcloud_topic: /magv/scan/3d
world_goal_topic: /world_goal
subtasks_topic: /subtasks
core_feedback_topic: /core_feedback
vln_status_topic: /vln_status
