#!/usr/bin/env python3

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Dict, Iterable, List
from urllib.error import HTTPError, URLError
from urllib.parse import quote
from urllib.request import Request, urlopen


ROOT = Path(__file__).resolve().parents[1]
MANIFESTS = ROOT / "sim" / "manifests"
GENERATED = ROOT / "sim" / "worlds" / "generated"
FUEL_CACHE = ROOT / "sim" / "cache" / "assets" / "fuel"
CHECKSUMS_FILE = MANIFESTS / "checksums.txt"
USER_AGENT = "vln-assets-sync/1.0"


def _fetch_bytes(url: str) -> bytes:
    request = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(request, timeout=60) as response:
        return response.read()


def _fetch_json(url: str) -> dict:
    return json.loads(_fetch_bytes(url).decode("utf-8"))


def _model_api_root(owner: str, name: str) -> str:
    return f"https://fuel.gazebosim.org/1.0/{quote(owner)}/models/{quote(name)}"


def _flatten_file_tree(nodes: Iterable[dict]) -> List[str]:
    paths: List[str] = []
    for node in nodes:
        children = node.get("children") or []
        if children:
            paths.extend(_flatten_file_tree(children))
            continue
        path = str(node.get("path", "")).lstrip("/")
        if not path or path.startswith("thumbnails/"):
            continue
        paths.append(path)
    return sorted(paths)


def _write_binary(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(payload)


def _model_checksum(model_dir: Path) -> str:
    digest = hashlib.sha256()
    for file_path in sorted(path for path in model_dir.rglob("*") if path.is_file() and path.name != ".fuel-model.json"):
        digest.update(str(file_path.relative_to(model_dir)).encode("utf-8"))
        digest.update(hashlib.sha256(file_path.read_bytes()).digest())
    return digest.hexdigest()


def _sync_fuel_model(entry: dict, offline: bool) -> str:
    owner = entry["owner"]
    name = entry["name"]
    api_root = _model_api_root(owner, name)
    target_dir = ROOT / entry["cache_dir"]
    model_sdf = target_dir / "model.sdf"
    model_config = target_dir / "model.config"
    cache_ready = model_sdf.exists() and model_config.exists()

    metadata = None
    files = None
    if not offline:
        try:
            metadata = _fetch_json(api_root)
            files = _fetch_json(f"{api_root}/tip/files")
        except (HTTPError, URLError, TimeoutError, ValueError) as exc:
            if cache_ready:
                print(f"[assets] using cached Fuel model '{name}' because metadata fetch failed: {exc}", file=sys.stderr)
            else:
                raise RuntimeError(f"failed to fetch Fuel metadata for '{name}': {exc}") from exc

    if metadata is not None:
        expected_version = entry.get("version")
        if expected_version is not None and int(metadata.get("version", -1)) != int(expected_version):
            raise RuntimeError(
                f"Fuel model '{name}' version drifted: expected {expected_version}, got {metadata.get('version')}"
            )
        _write_binary(target_dir / ".fuel-model.json", json.dumps(metadata, indent=2, sort_keys=True).encode("utf-8"))

    if files is not None:
        for relative_path in _flatten_file_tree(files.get("file_tree", [])):
            destination = target_dir / relative_path
            if destination.exists():
                continue
            download_url = f"{api_root}/tip/files/{quote(relative_path, safe='/')}"
            _write_binary(destination, _fetch_bytes(download_url))
        cache_ready = model_sdf.exists() and model_config.exists()

    if not cache_ready:
        mode = "offline cache validation" if offline else "download"
        raise RuntimeError(f"Fuel model '{name}' is incomplete after {mode}: expected {model_sdf} and {model_config}")

    checksum = _model_checksum(target_dir)
    print(f"[assets] ready {name} -> {target_dir.relative_to(ROOT)}")
    return checksum


def _stage_worlds(world_manifest: dict) -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    for world in world_manifest["worlds"]:
        template_path = ROOT / world["template"]
        output_path = GENERATED / f"{world['name']}.world"
        output_path.write_text(template_path.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"[assets] staged {output_path.relative_to(ROOT)}")


def _write_checksums(robot_manifest: dict, world_manifest: dict, fuel_checksums: Dict[str, str]) -> None:
    lines = [
        "# Generated by tools/sync_assets.py",
        f"robots/{robot_manifest['uav']['name']} PENDING",
        f"robots/{robot_manifest['rover_stub']['name']} PENDING",
    ]
    for model in world_manifest.get("fuel_models", []):
        checksum = fuel_checksums.get(model["name"], "MISSING")
        lines.append(f"fuel/{model['name']} {checksum}")
    CHECKSUMS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Download curated outdoor assets and stage Gazebo worlds.")
    parser.add_argument("--offline", action="store_true", help="Use cached assets only and skip network requests.")
    args = parser.parse_args()

    robot_manifest = json.loads((MANIFESTS / "robots.lock.yaml").read_text(encoding="utf-8"))
    world_manifest = json.loads((MANIFESTS / "world_assets.lock.yaml").read_text(encoding="utf-8"))

    FUEL_CACHE.mkdir(parents=True, exist_ok=True)
    fuel_checksums: Dict[str, str] = {}
    for model in world_manifest.get("fuel_models", []):
        fuel_checksums[model["name"]] = _sync_fuel_model(model, offline=args.offline)

    _stage_worlds(world_manifest)
    _write_checksums(robot_manifest, world_manifest, fuel_checksums)


if __name__ == "__main__":
    main()
